markdown: redcarpet
baseurl: /switch
exclude: ['README.md']
prose:
	rooturl: '_posts'
	siteurl: 'http://imurek.github.io/switch/'
	media: 'post_media'
	relativeLinks: 'docs/links.jsonp'
	ignore:
	    - index.html
	    - _config.yml
	    - /_layouts
	    - /_includes

	metadata: 
		_posts:
		  - name: 'layout'
			field: 
				element: 'hidden'
				value: 'post'
