markdown: redcarpet
baseurl: /switch
exclude: ['README.md']
permalink: pretty
prose:
  rooturl: '_posts'
  siteurl: 'http://imurek.github.io/switch/'
  relativeLinks: 'http://imurek.github.io/switch/docs/links.jsonp'
  media: 'post_media'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata: 
    _posts:
	  - name: 'layout'
	    field: 
		  element: 'hidden'
		  value: 'post'
