markdown: redcarpet
exclude: ["README.md"]
permalink: pretty
prose:
  rooturl: '_posts'
  siteurl: 'http://switch-trial.ch/'
  media: 'post_media'
  metadata:
    _posts:
     - name: "layout"
       field:
         element: "hidden"
         value: "post"
