markdown: redcarpet
baseurl: /switch
exclude: ["README.md"]
permalink: pretty
prose:
  rooturl: '_posts'
  media: 'post_media'
  metadata:
    _posts:
     - name: "layout"
       field:
         element: "hidden"
         value: "post"
     - name: "excerpt"
       field:
         element: "textarea"
         label: "Excerpt"
         help: "Short summary of the article..."
